#%RAML 1.0
title: cloudhub-api2

/sample:
  get:
    responses:
      200:
        body:
          application/json:
            example:
              {
                "message" : "success"
              }